### ISSUE TITLE
Add unary epsilon-indicator

### ISSUE THREAD

**Issue by jmejia8** [jmejia8/Metaheuristics.jl#21]
Implement the unary epsilon-indicator detailed in 

> Zitzler, E., Thiele, L., Laumanns, M., Fonseca, C. M., & da Fonseca, V. G. (2003). Performance assessment of multiobjective optimizers: an analysis and review. IEEE Transactions on Evolutionary Computation, 7(2), 117–132. doi:10.1109/TEVC.2003.810758 (https://doi.org/10.1109/TEVC.2003.810758)

**Comment by jmejia8** [comment]
@mtzrene suggested this integration. However, I have some questions about it.
What is the difference between the additive and multiplicative variants of the unary epsilon-indicator.

**Comment by jmejia8** [comment]
An implementation in https://github.com/jmejia8/Metaheuristics.jl/commit/7e8ba054185f178dd8eb5751b42beedade9f9c85
Docstring: https://jmejia8.github.io/Metaheuristics.jl/dev/indicators/#\\varepsilon-Indicator

**Comment by mtzrene** [comment]
@jmejia8 An apology, it has been many days.

The main difference between one and the other is the following: the multiplicative is basically how much you need to multiply one Pareto front (approximate front) to dominate another. The additive, is how much you need to add to have dominance.

By the way, I saw that you are from Mexico, me too. I am currently studying a Ph.D. at CICESE. I am very interested in optimization and currently in reinforcement learning. I am learning Julia, because I have seen that it has a lot of goodness.

**Comment by mtzrene** [comment]
@jmejia8 Thank you for adding the epsilon indicator. I will use it with some data I have there.

**Comment by jmejia8** [comment]
Thanks for clarifying such differences! I hope my implementation of the epsilon-indicator can be useful for the community.

Nice! I'm finishing my Ph.D. in AI at IIIA (Veracruz 🐠). IMO, learning Julia is the best decision you can make.
BTW, you can reach me on [Twitter (_jmejia)](https://twitter.com/_jmejia) for further collaboration on optimization topics.

**Comment by jmejia8** [comment]
This new performance indicator is implemented from [Metaheuristics.jl v3.2.8](https://github.com/jmejia8/Metaheuristics.jl/releases/tag/v3.2.8). You only need to update.
