### ISSUE TITLE
Multi-threading fitness calculations

### ISSUE THREAD

**Issue by jbytecode** [jmejia8/Metaheuristics.jl#22]
The vast majority of the calculation times is based on fitness calculations in optimization algorithms.

For example, in a GA, the operators selection, crossover, and mutation are not heavy or costy calculations, however, calculation of a fitness value can take several seconds - in such cases, it can take minutes.

How about calculating fitness values in different threads? The `Threads.thread` macro would be a solution. `ThreadsX` package presents a multi-threaded version of `map().` 

Letting m() a multi-threading map() function

`m(f, population)`

would increase the computation time with its easy implementation.
 
This issue is only a recommendation, any thoughts are welcome.

**Comment by jmejia8** [comment]
Thank's for your valuable recommendation. The current state of Metaheuristics does not implement multi-thread calculations.
However, it implements batch evaluations that let some parallel implementation out of this package.

Here is an example.

```julia
julia> f, bounds, _ = Metaheuristics.TestProblems.rastrigin();

julia> function f_parallel(X)
           fitness = zeros(size(X,1))
           Threads.@threads for i in 1:size(X,1)
               fitness[i] = f(X[i,:])
           end
           fitness
       end

julia> options = Options(parallel_evaluation=true,seed=1);

julia> ga = GA(;mutation=PolynomialMutation(;bounds),
                crossover=SBX(;bounds),
                options
                );

julia> optimize(f_parallel, bounds, ga)
+=========== RESULT ==========+
  iteration: 500
    minimum: 0.000246466
  minimizer: [-0.0008699292241303138, -4.2629790119100774e-7, -1.7561329420946332e-5, -9.238589200889676e-5, -0.0005059045206149494, -9.541041769354155e-5, -0.0003294316568515557, 0.00013695162554667605, -7.510307339887128e-6, 0.0002903779231362525]
    f calls: 50000
 total time: 0.6031 s
stop reason: Maximum number of iterations exceeded.
+============================+

```

[Here](https://jmejia8.github.io/Metaheuristics.jl/stable/examples/#Batch-Evaluation) is another example considering constraints.

I hope this multi-thread evaluation is implemented in the future within Metaheuristics. At the current time, I'm incapable of doing it in a stable way due to not every metaheuristic being able to perform parallel evaluations. Let me check `ThreadsX` for possible integration. Contributions are welcome!

**Comment by jmejia8** [comment]
Maybe, I should add this example to the documentation.

**Comment by fakhriaunur** [comment]
Combining @jbytecode idea to @jmejia8  example :

```julia
julia> function f_parallel(X)
           fitness = zeros(size(X,1))
           ThreadsX.map!(i->sum(X[i,:]),fitness,1:size(X,1))
           fitness
       end
```

**Comment by jbytecode** [comment]
is it the correct time to close this issue?

**Comment by jmejia8** [comment]
Just a last comment. See this [Tutorial](https://jmejia8.github.io/Metaheuristics.jl/dev/tutorials/parallelization/) for further examples of parallel function evaluations.

**Comment by jbytecode** [comment]
@jmejia8 - nice documentation, I will take a look at this when I need parallelism, thank you for preparing such a great package.
